### ISSUE TITLE
Back-end > update user settings

### ISSUE THREAD

**Issue by AlexSugak** [AlexSugak/getsky-trade#11]
Add new API endpoint used to update user settings, e.g. CountryCode, Preferred Currency, TimeZone etc.

e.g. POST api/me/settings

**Comment by kostyaVyrodov** [comment]
@AlexSugak , 
I think the POST method is not suitable for such endpoint and we should use PUT instead of POST. 
That's because the endpoint doesn't create anything, it just update user's details. 
The insert is performed during execution of RegisterHandler.

**Comment by AlexSugak** [comment]
@kostyaVyrodov it is not about insert vs. update, the question is if there is a side effect. I agree that in this case we can go with PUT as updating user settings should not trigger any event with a side effect
