### ISSUE TITLE
Advert details page

### ISSUE THREAD

**Issue by alexey-belous** [AlexSugak/getsky-trade#19]
Create page with detailed information of advert post.

**Comment by alexey-belous** [comment]
@AlexSugak, in case when user comes to advert post that isn't exists we should show 404 page to them. Do we need to implement '404 error handling' in scope of this issue or we will implement one mechanism of error handling for all requests (e.g. using middleware)?

**Comment by AlexSugak** [comment]
@alexey-belous  I think in this specific case we could show a special page like "advert not found or no longer exists", let's not go into middleware yet and implement a custom 404 error handling for this page.
